name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: npm run release
      - name: Get release version
        id: get_version
        run: echo "version=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV
      - name: Create release pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: release/v${{ env.version }}
          base: main
          title: chore(release): v${{ env.version }}
          body: Release v${{ env.version }}
      - name: Push release tag
        run: git push origin v${{ env.version }}
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
